Inserted docstring for two dimensional sor
cwehmeyer/urban-broccoli pull request #14
Opened 2017-11-21 10:55 UTC by zenoone

I inserted the docstrings

2017-11-21 11:01 UTC, cwehmeyer commented
meh, fix your typos!

2017-11-21 13:25 UTC, cwehmeyer requested changes
Please check your indentions and fix typos

2017-11-22 09:26 UTC, zenoone commented
could you be a bit more specific please, 
how should indentions look like?
thanks

2017-11-24 12:56 UTC, cwehmeyer requested changes
Please look at the three exemplary notes and make sure that the entire docstring fits that scheme

2017-11-24 12:56 UTC, cwehmeyer commented on urbanbroccoli/sor.py
> +    """Performs a sucsessive over-relaxation for the Poisson equation of a two dimensional discretized charge distribution:
This line has the correct indention but is too long. Use a very short description and, if necessary, a longer text block after two line breaks.

2017-11-24 12:56 UTC, cwehmeyer commented on urbanbroccoli/sor.py
>            Parameters:
This line has an indention level of 10 spaces. Indentions should be multiples of four and, most important, they should be consistent. Use an indention level of four spaces, here.

2017-11-24 12:56 UTC, cwehmeyer commented on urbanbroccoli/sor.py
>              rho (ndarray)
Lines 36-49: remove four spaces indention.

2017-11-25 14:01 UTC, cwehmeyer approved these changes

2017-11-25 14:01 UTC, cwehmeyer commented on urbanbroccoli/sor.py
> +    Parameters:
This is what I had in mind.

2017-11-25 14:02 UTC, merged